---
- hosts: dockerhost
  tasks:
    - name: performing docker image prune on docker host
      shell:
        cmd: docker image prune -f -a --filter "until=240h"
    - name: performing docker container prune on docker host
      shell:
        cmd: docker container prune -f